name: Build

on:
    push:
      branches: [ "main" ]

env:
    SVC_NAME: sk-example-app

jobs:
  deploy:
    name: Deploy to Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # TODO: Use this when ready to push
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            push: false
            tags: zerodaysec/${{ env.SVC_NAME }}:main
